"""add incident idempotency constraint

Revision ID: a9553b444619
Revises: a3872126a783
Create Date: 2026-08-28 00:45:00.683565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9553b444619'
down_revision: Union[str, Sequence[str], None] = 'a3872126a783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_incidents_payment_order_type', 'incidents', ['payment_id', 'order_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_incidents_payment_order_type', 'incidents', type_='unique')
    # ### end Alembic commands ###
